name: Pull request

on: [ pull_request ]

jobs:
  test:
    name: Unit tests
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: ./gradlew test --stacktrace

      - name: Upload testDebugUnitTest results
        uses: actions/upload-artifact@v2.2.3
        if: failure()
        with:
          name: testDebugUnitTest
          path: ./**/build/reports/tests/testDebugUnitTest

      - name: Upload allTests results
        uses: action/upload-artifact@v2.2.3
        if: failure()
        with:
          name: allTests
          path: ./**/build/reports/test/allTests
